### PR TITLE
Remove sourcelink dependency

### PR DESCRIPTION
**Pull request by NikolaMilosavljevic**
Contributes to https://github.com/dotnet/source-build/issues/3551

Sourcelink dependency isn't needed anymore. Arcade uses sourcelink tooling that is included in .NET SDK 8.0 preview 6.

### CODE REVIEW

**Comment by NikolaMilosavljevic** [comment]
cc @mmitche @dotnet/source-build-internal

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
This repo will need the arcade update.

**Comment by NikolaMilosavljevic** [comment]
> This repo will need the arcade update.

Yeah - that is breaking the source-build leg.

**Comment by mmitche** [comment]
> > This repo will need the arcade update.
> 
> Yeah - that is breaking the source-build leg.

You could merge the arcade update branch in here to unblock things,

**Review by mmitche — APPROVED** [review]

**Pull request merged**
