### PR TITLE
Implement common helpers as extension methods

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@KevinH-MS FYI. Moving a helpers we use in Roslyn to read Windows PDBs to DiaSymReader as public APIs.

**Comment by KevinH-MS** [comment]
No complaints here! :+1: 

Was there anything you materially altered, or just copying code and changing the signature to extension methods?

Also, out of curiosity, how big is the new binary?

**Comment by tmat** [comment]
@KevinH-MS Some minor changes were needed. E.g. the APIs return regular array, not ImmutableArray since the DSR can't have dependency on immutable collections.

**Comment by tmat** [comment]
Release dll size grew from 25,032B to 30,720B.

**Pull request merged**
